// <auto-generated />
using System;
using Meetmind.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meetmind.Infrastructure.Migrations
{
    [DbContext(typeof(MeetMindDbContext))]
    [Migration("20250513153411_InitialcreateSetting")]
    partial class InitialcreateSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Meetmind.Domain.Entities.SettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStartRecord")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSummarize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTranscript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTranslate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyBeforeMinutesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
